version: '3'
services:
  ffmpeg:
    image: jrottenberg/ffmpeg:3.3
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      HOST_NAME: db
      SERVER_NAME: 0.0.0.0
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 1122
    depends_on:
      db:
        condition: service_healthy
        restart: true

    volumes:
      - /test-flask/data
    links:
      - db
  db:
    image: postgres
    restart: always
    ports:
      - 5433:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
