version: '3'
services:
#  web:
#    build: .
#    ports:
#      - "80:8000"
#    depends_on:
#      db:
#        condition: service_healthy
#    command: ["python", "app.py"]

  db:
      image: postgres
      restart: always
      environment:
        POSTGRES_PASSWORD: admin
      healthcheck:
        test: ["CMD-SHELL", "pg_isready"]
        interval : 1s
        timeout: 5s
        retries: 10
